### ISSUE TITLE
Wrong Error Message on Early Work Start

### ISSUE THREAD

**Issue by denrase** [mbrugger/timetracking#22]
Work start was at 7:30.

Is:
An error message with the title "Ungültiger Arbeitsbeginn (vor 06:00)" is displayed in the pause column.

Expected:
- If the earliest time entry for working is 08:00, it should display correctly.
- It should be possible to setup the earliest work start or deactivate it for employments.

![62a5d2322db78515343dab8f4ad0a6b6](https://cloud.githubusercontent.com/assets/3984453/7019267/8900653a-dd0e-11e4-9239-f9315d654680.jpg)

**Comment by BYTEPOETS-MBR** [comment]
I suspect it to be related to validating time entries in UTC, will check this. This seems to be a bug.

Will create a separate feature request to disable/enable valdiation per customer

**Comment by denrase** [comment]
Sounds great, thank you! :)

**Comment by mbrugger** [comment]
Fixed in 0.9.1
