### ISSUE TITLE
HomeController#index not working if current day is leave day

### ISSUE THREAD

**Issue by BYTEPOETS-MBR** [mbrugger/timetracking#23]
App 73 stdout: Started GET "/" for 172.17.42.1 at 2015-04-14 20:29:08 +0000
App 73 stdout: Processing by HomeController#index as HTML
App 73 stdout:   Rendered time_entries/_day_time_entries.html.erb (1.5ms)
App 73 stdout:   Rendered home/index.html.erb within layouts/application (1.8ms)
App 73 stdout: Completed 500 Internal Server Error in 15ms
App 73 stdout: 
App 73 stdout: ActionView::Template::Error (Missing partial partials/_leave_day_type with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
App 73 stdout:   * "/home/app/timetracking-webapp/app/views"
App 73 stdout:   * "/var/lib/gems/2.1.0/gems/twitter-bootstrap-rails-3.2.0/app/views"
App 73 stdout:   * "/var/lib/gems/2.1.0/gems/devise-3.4.1/app/views"
App 73 stdout: ):
App 73 stdout:     36:       </tr>
App 73 stdout:     37:     <% end %>
App 73 stdout:     38:     <% else  %>
App 73 stdout:     39:     <tr><td colspan="5"><center><%= render "partials/leave_day_type", leave_day: @working_day.leave_day %></center></td></tr>
App 73 stdout:     40:     <% end %>
App 73 stdout:     41:   </tfoot>
App 73 stdout:     42: </table>
App 73 stdout:   app/views/time_entries/_day_time_entries.html.erb:39:in `_app_views_time_entries__day_time_entries_html_erb___1274281177074746491_48674120'
App 73 stdout:   app/views/home/index.html.erb:4:in `_app_views_home_index_html_erb__1425572061124736865_48609380'
App 73 stdout: 
App 73 stdout:

**Comment by mbrugger** [comment]
fixed
